# 语言文件 [可选 中文简体:zh_CN;中文繁體:zh_TW;English:en_US]
language: zh_CN

# 是否开启更新提醒,建议开启
isCheckUpdate: true

# op登录时候是否发送更新提醒
isCheckUpdateToOpMsg: true

# 判断回归时间
returnDay: 7

# 回归的总天数,到期移除回归身份(不建议修改)
endDay: 7